# Generated by Django 3.2.11 on 2022-01-13 12:53

from django.db import migrations, models
import django.db.models.deletion
# import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='static/img/videosLogo')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                # ('content', froala_editor.fields.FroalaField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('courseTitle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.course')),
            ],
        ),
    ]
