# Generated by Django 3.2.11 on 2022-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='content',
            field=models.TextField(),
        ),
    ]
