# Generated by Django 3.2.11 on 2022-01-21 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_alter_playlist_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('commentText', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursecomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
