# Generated by Django 3.2.11 on 2022-01-23 10:53

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('course', '0003_coursecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='postTag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
