# Generated by Django 3.2.11 on 2022-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='contentDesc',
            field=models.TextField(blank=True),
        ),
    ]
