# Generated by Django 3.2.11 on 2022-01-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_playlist_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='Tags',
            new_name='tags',
        ),
    ]
