# Generated by Django 3.2.11 on 2022-01-19 16:21

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('postTitle', models.CharField(max_length=300)),
                ('postSlug', models.SlugField()),
                ('postContent', models.TextField()),
                ('postImg', models.ImageField(upload_to='static/blog/blogImg/postImg')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('postTag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
