# Generated by Django 3.2.11 on 2022-01-21 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220120_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentReply',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('commentText', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomment')),
            ],
        ),
    ]
