# Generated by Django 3.2.11 on 2022-01-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_blogcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='postContentFile',
            field=models.FileField(blank=True, upload_to='static/blog/blogPost/postFile'),
        ),
    ]
