# Generated by Django 3.2.11 on 2022-01-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_postcontentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='postContentFile',
        ),
    ]
