# Generated by Django 3.2.11 on 2022-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogpost_postcontentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='postDesc',
            field=models.TextField(blank=True),
        ),
    ]
